### ISSUE TITLE
Panic while doing concurrent calls

### ISSUE THREAD

**Issue by elgatito** [likexian/doh-go#1]
Hello, 

I'm trying your package for making DNS resolve, and got a panic, when resolver was used by different coroutines for same domain name.

Here is the log cut:
```
2019-08-19 22:53:47.030 T:140301298595584  NOTICE: [plugin.video.elementum] fatal error: concurrent map writes
2019-08-19 22:53:47.030 T:140301298595584  NOTICE: [plugin.video.elementum]
2019-08-19 22:53:47.030 T:140301298595584  NOTICE: [plugin.video.elementum] goroutine 965 [running]:
2019-08-19 22:53:47.030 T:140301298595584  NOTICE: [plugin.video.elementum] runtime.throw(0x167b30d, 0x15)
2019-08-19 22:53:47.030 T:140301298595584  NOTICE: [plugin.video.elementum] 	/home/elgato/gobin/src/runtime/panic.go:617 +0x72 fp=0xc000551838 sp=0xc000551808 pc=0x543902
2019-08-19 22:53:47.030 T:140301298595584  NOTICE: [plugin.video.elementum] runtime.mapassign_faststr(0x158a3e0, 0xc0002c2870, 0x16698f8, 0x6, 0xc0006318c0)
2019-08-19 22:53:47.031 T:140301298595584  NOTICE: [plugin.video.elementum] 	/home/elgato/gobin/src/runtime/map_faststr.go:291 +0x40f fp=0xc0005518a0 sp=0xc000551838 pc=0x52918f
2019-08-19 22:53:47.031 T:140301298595584  NOTICE: [plugin.video.elementum] net/textproto.MIMEHeader.Set(...)
2019-08-19 22:53:47.031 T:140301298595584  NOTICE: [plugin.video.elementum] 	/home/elgato/gobin/src/net/textproto/header.go:22
2019-08-19 22:53:47.031 T:140301298595584  NOTICE: [plugin.video.elementum] net/http.Header.Set(...)
2019-08-19 22:53:47.031 T:140301298595584  NOTICE: [plugin.video.elementum] 	/home/elgato/gobin/src/net/http/header.go:37
2019-08-19 22:53:47.031 T:140301298595584  NOTICE: [plugin.video.elementum] github.com/likexian/gokit/xhttp.(*Request).SetHeader(0xc000234380, 0x1669e32, 0x6, 0x1679cde, 0x14, 0xc000551f01)
2019-08-19 22:53:47.031 T:140301298595584  NOTICE: [plugin.video.elementum] 	/home/elgato/go/src/github.com/likexian/gokit/xhttp/xhttp.go:337 +0xc3 fp=0xc0005518f8 sp=0xc0005518a0 pc=0xca50d3
2019-08-19 22:53:47.031 T:140301298595584  NOTICE: [plugin.video.elementum] github.com/likexian/gokit/xhttp.(*Request).Do(0xc000234380, 0x1667834, 0x3, 0x168cbd3, 0x24, 0xc000551e80, 0x3, 0x3, 0x0, 0x0, ...)
2019-08-19 22:53:47.032 T:140301298595584  NOTICE: [plugin.video.elementum] 	/home/elgato/go/src/github.com/likexian/gokit/xhttp/xhttp.go:526 +0x291e fp=0xc000551d90 sp=0xc0005518f8 pc=0xca885e
2019-08-19 22:53:47.032 T:140301298595584  NOTICE: [plugin.video.elementum] github.com/likexian/gokit/xhttp.(*Request).Get(...)
2019-08-19 22:53:47.032 T:140301298595584  NOTICE: [plugin.video.elementum] 	/home/elgato/go/src/github.com/likexian/gokit/xhttp/xhttp.go:285
2019-08-19 22:53:47.032 T:140301298595584  NOTICE: [plugin.video.elementum] github.com/likexian/doh-go/provider/cloudflare.(*Provider).ECSQuery(0xc000033e00, 0x18545c0, 0xc000225680, 0xc0006177b0, 0xc, 0x16672ec, 0x1, 0x0, 0x0, 0x0, ...)
2019-08-19 22:53:47.032 T:140301298595584  NOTICE: [plugin.video.elementum] 	/home/elgato/go/src/github.com/likexian/doh-go/provider/cloudflare/cloudflare.go:111 +0x3b3 fp=0xc000551ec0 sp=0xc000551d90 pc=0xcab413
2019-08-19 22:53:47.032 T:140301298595584  NOTICE: [plugin.video.elementum] github.com/likexian/doh-go.(*DoH).fastECSQuery.func1(0x18545c0, 0xc000225680, 0xc0006177b0, 0xc, 0x16672ec, 0x1, 0x0, 0x0, 0xc000238f50, 0xc000039140, ...)
2019-08-19 22:53:47.032 T:140301298595584  NOTICE: [plugin.video.elementum] 	/home/elgato/go/src/github.com/likexian/doh-go/doh.go:200 +0xb1 fp=0xc000551f78 sp=0xc000551ec0 pc=0xcaf681
2019-08-19 22:53:47.033 T:140301298595584  NOTICE: [plugin.video.elementum] runtime.goexit()
2019-08-19 22:53:47.033 T:140301298595584  NOTICE: [plugin.video.elementum] 	/home/elgato/gobin/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000551f80 sp=0xc000551f78 pc=0x573181
2019-08-19 22:53:47.033 T:140301298595584  NOTICE: [plugin.video.elementum] created by github.com/likexian/doh-go.(*DoH).fastECSQuery
2019-08-19 22:53:47.033 T:140301298595584  NOTICE: [plugin.video.elementum] 	/home/elgato/go/src/github.com/likexian/doh-go/doh.go:199 +0x1e0
```

**Comment by likexian** [comment]
Hello @elgatito 
This has been fixed, please have a new try.
Thank you for feedback.

**Comment by elgatito** [comment]
Gave a quick test and it looks fine!
Thanks for quick change!
